### ISSUE TITLE
50% of fees redirected to a third party wallet

### ISSUE THREAD

**Issue by cryptoh0x** [PartyDAO/erc20-creator#24]
Hey,
I'm looking at your deployed contract at https://basescan.org/address/0x70d4511b04eb995d00066af35416a9ababa27e81
and it looks like the party DAO takes 50% of eth from LP fees.
This was not disclosed in the docs or any other source I could find.
Can you explain the fee structure and reasoning behind it?

**Comment by arr00** [comment]
This is a parameter specified in the constructor of the `FeeCollector`. https://github.com/PartyDAO/erc20-creator/blob/a24465781ce89aa2edec8791ceb29517ce56d0ea/src/FeeCollector.sol#L40-L45

The fee is disclosed on the frontend.
